version: '3.2'

volumes:
    db_volume:
    frontend_code:
    backend_code:
    apache_site:

services:
    database:
        container_name: iot-portal-database
        image: iot-portal-database-image
        stdin_open: true
        tty: true
        restart: always
        build:
            context: ./
            dockerfile: ./mysql/Dockerfile
        ports:
           - '8001:3306'
        networks:
            - backend
        volumes:
            - db_volume:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password

    frontend:
        container_name: iot-portal-frontend
        image: iot-portal-frontend-image
        stdin_open: true
        tty: true
        restart: always
        build:
            context: ./
            dockerfile: ./frontend/Dockerfile
        ports:
            - "8002:8080"
        networks:
            - frontend
            - backend
        volumes:
            - frontend_code:/srv/www/

    backend:
        container_name: iot-portal-backend
        image: iot-portal-backend-image
        stdin_open: true
        tty: true
        restart: always
        networks:
            - backend
        build:
            context: ./
            dockerfile: ./php/Dockerfile
        volumes:
            - backend_code:/srv/www/
            - ${PHP_CONFIG}/:/tmp/php-config/

    web:
        container_name: web
        image: web-image
        stdin_open: true
        tty: true
        restart: always
        build:
            context: ./
            dockerfile: ./apache/Dockerfile
        ports:
            - "8003:80"
        networks:
            - frontend
            - backend    
        volumes:
            - backend_code:/srv/www/
            - apache_site:/etc/apache2/sites-enabled
            - ${APACHE_SITE}/:/etc/apache2/sites-available
        depends_on:
            - database
            - backend
        environment:
            FPM_HOST: iot-portal-backend:9000

networks:
    frontend:
    backend: